server:
  port: 8080

spring:
  datasource:
    hikari:
      maximum-pool-size: 4
    url: jdbc:mariadb://redsky21-db1.cb1vehi7zfck.ap-northeast-2.rds.amazonaws.com:3306/redsky21_db1
    username: admin
    password: chae2121!

mybatis:
  mapper-locations: mapper/*.xml