server:
  port: 8080

spring:
  datasource:
    hikari:
      maximum-pool-size: 4
      core:
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        jdbc-url: jdbc:log4jdbc:mariadb://redsky21-db1.cb1vehi7zfck.ap-northeast-2.rds.amazonaws.com:3306/redsky21_db1
        username: admin
        password: ENC(ygFNq7EQhAmpEamBGAqudiERJjmFX4mr)
      b2b:
        driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy  #로컬에서만 사용
        jdbc-url: jdbc:log4jdbc:mariadb://10.185.176.25:3310/espsald?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC8&allowMultiQueries=true
        username: sal_app
        password: 'lwhi33!ct'

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

logging:
  level:
    root: info

mybatis:
  mapper-locations: mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true